#!/bin/sh

ENABLED=yes
PROCS=VPNremote-daemon
ARGS="-c /opt/etc/VPNremote"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# check and remove stale pid
if ! pidof VPNremote-daemon 1>/dev/null 2>&1; then
	rm -f /opt/var/run/VPNremote.pid
fi

. /opt/etc/init.d/rc.func
